### ISSUE TITLE
Projektbeschreibung

### ISSUE THREAD

**Issue by ZeroSoulEater** [smarthome-lab/chat-app#1]
Hier evtl die Projektbeschreibung als PDF ablegen

**Comment by AndyRandie** [comment]
[Weiterentwicklung der Chat.pdf](https://github.com/smarthome-lab/chat-app/files/2008252/Weiterentwicklung.der.Chat.pdf)

**Comment by AndyRandie** [comment]
Update Projektbeschreibung
[Weiterentwicklung der Chat.pdf](https://github.com/smarthome-lab/chat-app/files/2008269/Weiterentwicklung.der.Chat.pdf)
